name: flutter_chat_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  get: 4.6.6
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  introduction_screen: ^3.1.14
  font_awesome_flutter: ^10.7.0
  avatar_glow: ^3.0.1
  emoji_picker_flutter: ^2.2.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.1.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  extended_image: ^8.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo-chats.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/logo-chats.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/logo-chats.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/logo-chats.png'
