// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiV5-uGWTK62M7ChNLX5RYiVkMssVIwQw',
    appId: '1:583221988395:web:0a39c961155e73bf3e6e6e',
    messagingSenderId: '583221988395',
    projectId: 'flutter-chat-apps-84f4b',
    authDomain: 'flutter-chat-apps-84f4b.firebaseapp.com',
    storageBucket: 'flutter-chat-apps-84f4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7QD6I7tlyiW8nJLTgTRvQ-BuHvhogaNE',
    appId: '1:583221988395:android:b07146f3daab1e083e6e6e',
    messagingSenderId: '583221988395',
    projectId: 'flutter-chat-apps-84f4b',
    storageBucket: 'flutter-chat-apps-84f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdqxTrLUdY89A7ij0IcQXQR3VfTNmiRA',
    appId: '1:583221988395:ios:21d28e75b778c3eb3e6e6e',
    messagingSenderId: '583221988395',
    projectId: 'flutter-chat-apps-84f4b',
    storageBucket: 'flutter-chat-apps-84f4b.appspot.com',
    iosBundleId: 'com.example.flutterChatApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwdqxTrLUdY89A7ij0IcQXQR3VfTNmiRA',
    appId: '1:583221988395:ios:21d28e75b778c3eb3e6e6e',
    messagingSenderId: '583221988395',
    projectId: 'flutter-chat-apps-84f4b',
    storageBucket: 'flutter-chat-apps-84f4b.appspot.com',
    iosBundleId: 'com.example.flutterChatApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiV5-uGWTK62M7ChNLX5RYiVkMssVIwQw',
    appId: '1:583221988395:web:c87d7471ac61712c3e6e6e',
    messagingSenderId: '583221988395',
    projectId: 'flutter-chat-apps-84f4b',
    authDomain: 'flutter-chat-apps-84f4b.firebaseapp.com',
    storageBucket: 'flutter-chat-apps-84f4b.appspot.com',
  );
}
